### ISSUE TITLE
Detached Fork

### ISSUE THREAD

**Issue by RainbowZephyr** [mamantoha/shards-info#125]
Hello, 
I have a detached fork from another crystal repo and it is not showing up on the website, is there something I should do?

Thanks in advance

**Comment by mamantoha** [comment]
Hi @RainbowZephyr , The GitHub API doesn't provide forked repositories. If it's a dependency of another repository, it will be included. Alternatively, you can share a link, and I'll manually add it.

**Comment by RainbowZephyr** [comment]
It is not a dependency, the link as below:
https://github.com/RainbowZephyr/dsp

Thank you so much :smile:

**Comment by mamantoha** [comment]
https://shards.info/github/RainbowZephyr/dsp done
