### ISSUE TITLE
Getting up and running locally

### ISSUE THREAD

**Issue by robacarp** [mamantoha/shards-info#138]
Hi @mamantoha 

I'd like to get shards-info up and running on my local computer as a use case for a third-party deployed site which uses mosquito. The instructions in the readme helped, but not everything was covered.

In particular, the .env.example file has these declarations which I'm not confident I know how to get, or which are optional:

GITHUB_USER=
GITHUB_KEY=
GITLAB_ACCESS_TOKEN=
SENTRY_DSN=
GOOGLE_ANALYTICS_ID=
GITHUB_CLIENT_ID=
GITHUB_CLIENT_SECRET=

Do I need all of these? For those that I do need, can you link me to documentation on how to configure the secrets? For example, I don't understand GITHUB_KEY and GITHUB_CLIENT_SECRET -- but I've never built anything with the github API.

**Comment by mamantoha** [comment]
@robacarp If necessary, I can provide a database dump for you.
