### ISSUE TITLE
Add GitLab source

### ISSUE THREAD

**Issue by AlexWayfer** [mamantoha/shards-info#32]
Shards exist on GitLab.com, for example: https://gitlab.com/jgillich/crystal-dns

**Comment by mamantoha** [comment]
shards-info only works with github.

In the code "gitlab" only used to show icon and link (if it exists in `shards.yml` file) to gitlab for dependencies.
For example https://shards.info/repos/mswieboda/tradify

**Comment by AlexWayfer** [comment]
> shards-info only works with github.
> 
> In the code "gitlab" only used to show icon and link (if it exists in shards.yml file) to gitlab for dependencies.
> For example https://shards.info/repos/mswieboda/tradify

Okay, thank you, sorry. I've updated the issue.

> P.S. And this will not be implemented due to the limitations of the Gitlab API disappointed

Which limitations? There: https://docs.gitlab.com/ee/user/gitlab_com/index.html#gitlabcom-specific-rate-limits

I see:

> For assistance, contact GitLab Support with details, such as the affected IP address.

**Comment by mamantoha** [comment]
The main issue is Gitlab API doesn't support filtering by language.

**Comment by AlexWayfer** [comment]
> The main issue is Gitlab API doesn't support filtering by language.

There: https://docs.gitlab.com/ee/api/projects.html#list-all-projects

I see `with_programming_language` parameter. Isn't that what you're talking about?

**Comment by mamantoha** [comment]
yes, exactly 👏.

And it seems to work.

<img width="991" alt="Postman 2019-12-18 16-45-21" src="https://user-images.githubusercontent.com/61285/71095994-3b3f7380-21b6-11ea-8382-80f26f62d924.png">

I will check later how to integrate Gitlab into shards-info.

**Comment by mamantoha** [comment]
By the way. If you want to implement this yourself. PR is welcomed 🙏

**Comment by AlexWayfer** [comment]
I'm not sure that I'll have a time for that, but I'll write if it will.

**Comment by mamantoha** [comment]
@AlexWayfer 

Now http://shards.info website has Gitlab support.

https://shards.info/search?query=dns
https://shards.info/gitlab/jgillich/crystal-dns/

Closing.
