### ISSUE TITLE
Listing forks

### ISSUE THREAD

**Issue by didactic-drunk** [mamantoha/shards-info#59]
Can we get [forks](https://github.com/didactic-drunk/base32) listed by some mechanism when the [original project](https://github.com/noumar/base32) is no longer maintained?

I don't know what the criteria would be.  Possibly one or more of [no updates in x time, publishing releases, opt in, other].

**Comment by wyhaines** [comment]
I second this. I have some shards that I have forks for because the upstream shards appear to be abandoned. As some point, it makes sense to defer to a fork instead of the original when the fork is being maintained, while the original is not.

**Comment by mamantoha** [comment]
Hi @didactic-drunk. It's a simple wrapper around the Github AP, and it's maintaining its own database, and periodically sync data. I don't want to list forks at all. 

1. You can detach the fork and turn it into a standalone repository on GitHub. Contact GitHub Support (https://support.github.com/contact) and ask them to switch your repository to "normal mode". And this repository will automatically be listed on `shards.info`
2. I can manually add a fork by request.

**Comment by didactic-drunk** [comment]
Both of us have run in to an author not to be found so we've temporarily or permanently (unknown at the moment) taken over releases until their return.

If we unhook the fork (which I did for sodium.cr) there are downsides:
1. It won't show up under `forks` so existing projects can't find the new one except by searching.  How would anyone know to do that?
2. If the original is maintained again I want the fork back.  I don't think github will do that.  I could delete the project and create a new fork but then I lose issues/prs/discussions/etc

As crystal grows this will happen more and more.  Having a solution in place would be nice.

Also, I'd like my [base32](https://github.com/noumar/base32) fork listed.

**Comment by mamantoha** [comment]
Hi @didactic-drunk 

https://github.com/didactic-drunk/base32 added https://shards.info/github/didactic-drunk/base32/

**Comment by mamantoha** [comment]
fixed in https://github.com/mamantoha/shards-info/pull/102 and https://github.com/mamantoha/shards-info/pull/101
